#!/usr/bin/env bash
# Get a list of all Python files that are staged for commit

#Line length from PEP8 standard
LL="79"
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.py$' | xargs)
FORMATTER="black -l $LL"
CHECKER="black -l $LL --check --diff --color"
LINTER="pylint"

# If there are Python files staged for commit, run linter on them
#if [ -n "$STAGED_FILES" ]; then
#  echo "Running $LINTER on staged Python files..."
#fi

## Firs we run linter
#  $LINTER $STAGED_FILES
#  if [ "$?" != "0" ]; then
#    echo "ERROR: Some Python files are not structured properly. Please run:"
#    echo "To check:"
#    echo "    $LINTER ${STAGED_FILES}"
#    echo "Correct with care. Autofixes does not fix everything properly."
#    exit 1
#  fi
#fi

# Run black in check mode (it won't modify files, just checks for formatting issues)
if [ ! -z ${STAGED_FILES} ]; then
    $FORMATTER $STAGED_FILES

# If black returns a non-zero exit code (i.e., files aren't formatted correctly), exit with an error
    if [ "$?" != "0" ]; then
      echo "ERROR: Some Python files are not formatted correctly. Please run:"
      echo "To check:"
      echo "    $CHECKER ${STAGED_FILES}"
      echo "To correct:"
      echo "     $FORMATTER ${STAGED_FILES}"
      exit 1
    fi
fi

exit 0

